### ISSUE TITLE
[Enhancement] Add Grüvee Bot To PixelogicDev Discord

### ISSUE THREAD

**Issue by adilanchian** [PixelogicDev/gruveebackend#48]
### General
In the [PixelogicDev Discord](https://discord.gg/ubgX6T8) we have a #music channel. This channel is used for us to talk and share music with one another! I had the idea that it would be cool to have a bot that creates a "PixelogicDev Community Playlist" for Grüvee and this can be the first playlist for people who use the app to automatically have! Note - this is planned for our move from Alpha -> Beta launch in the next coming months

### Technical Thoughts
As we already have Firebase Functions to handle adding songs to a playlist, essentially at this point it's just creating the bot and hosting it somewhere. I would prefer this bot to be created in Node.js or if there is even a Golang library for Discord bots that would be awesome.

I see it as follows:

- I post a song link in #music 
- The bot recognizes it's a song link for one of the supported streaming providers
- Replies to the channel saying "Hey Alec I have added {InsertSongNameHere} to the PixleogicDev Community Playlist. Stay Grüvee!"
- Song addition goes through the regular add song flow we have in the app! 

### TODO

- [ ] Create bot repo for this
- [ ] Move this issue to that repo
- [ ] Setup initial bot
- [ ] Add call to endpoint for adding a song to a playlist
- [ ] Verify & test
...

**If you have any thoughts / ideas / concerns please make sure to leave them here!**

**Comment by LeviHarrison** [comment]
I think that Node.js might be the better option, but I did find this Discord Golang Library that looks pretty interesting:
https://github.com/bwmarrin/discordgo

And here's an example of a simple bot: https://github.com/bwmarrin/discordgo/blob/master/examples/pingpong/main.go

**Comment by adilanchian** [comment]
@LeviHarrison thanks for the feedback!

My first thought is I do agree it probably should be in Node.js / TS (yes let's start doing proper JS dev haha). I think it depends on our host. I think most cloud servers provide a Golang Runtime, but overall it may just be better to go Node.js

**Comment by adilanchian** [comment]
I finally got a raspberry pi :). Will be setting this up to have this bot hosted on this server!

**Comment by LeviHarrison** [comment]
Great!
